### PR TITLE
Add support for Node.js 6.x

### PR DESCRIPTION
**Pull request by marcobarcelos**
This pull request adds support for Node.js version 6.x (#425).
Built using node version 6.1.0 on a win x64 machine targeting both platforms.

### CODE REVIEW

**Comment by pendo324** [comment]
Just tested your commit against Node 6.2.0 and it seems to work

**Comment by eblumenfeld** [comment]
Could be possible to pull this request?
6.x support would be useful

**Comment by knight00931** [comment]
Yeah, I can confirm that works on my server (Node 6.2.1, Win10 x64 enterprise).
Hope this can be merged soon.

**Comment by adampaulberg** [comment]
Any chance we could get this PR's conflicts fixed and then merged? I've been running this for about a month, maybe two without issue on node 6.3.1. Node 6 support from the source would be great.

**Comment by timjroberts** [comment]
Any timelines on when this PR might go in?

**Comment by agracio** [comment]
All current versions of Node.Js supported in https://github.com/agracio/edge-js

**Pull request closed without merging**
