### PR TITLE
Workaround for unicode characters in path to double_edge.js

### PR DESCRIPTION
**Pull request by eNeRGy164**
Workaround for unicode characters in the path to `double_edge.js`. 

Should fix issues #278 and #481

### CODE REVIEW

**Comment by singstad** [comment]
What is the status of this fix?

**Comment by eNeRGy164** [comment]
Well, if the build could be restarted it should be done.

**Comment by olepetterlovik** [comment]
A workaround for this issue on windows is to make a directory symbolic link like:
mklink /D C:\Users\OlePetterL�vik C:\Users\OlePetterLøvik

I used process monitor to trace calls from func.exe process to get the call and actual characters..

**Comment by palaslet** [comment]
Any news on this?
Pretty important to have unicode support these days...

**Comment by jrincon23** [comment]
the work around given by @olepetterlovik  works like a charm, thank you!

**Pull request closed without merging**
