### PR TITLE
make edge works with node-chakracore

### PR DESCRIPTION
**Pull request by jianchun**
This PR makes edge work with [node-chakracore](https://github.com/nodejs/node-chakracore).

All the changes are for build/install scripts. Assuming precompiled binaries are not available (would also work if they are available), these changes enable "npm install" to build from source for the current node/npm platform.

### CODE REVIEW

**Comment by tjanczuk** [comment]
@jianchun thank you for this contribution, this is exciting. I will look through this in detail by end of the week. At this point I have two high level questions:

1. The PR does not seem to contain pre-built binary images of edge for the node-chakracore. Until now the release pattern for Edge.js on Windows was to ship pre-built binaries. Is there a reason this should be different for node-chakracore?

2. The PR appears to enable scripting CLR from Node.js using node-chakracore, but not the reverse. Scripting Node.js from CLR is enabled with a NuGet package built using https://github.com/tjanczuk/edge/blob/master/tools/build_double.bat. Is there a reason this would not be supported?

Thanks!

**Comment by jianchun** [comment]
@tjanczuk Thanks for prompt look!

> The PR does not seem to contain pre-built binary images of edge for the node-chakracore. Until now the release pattern for Edge.js on Windows was to ship pre-built binaries. Is there a reason this should be different for node-chakracore?

node-chakracore is new / beta and has very frequent releases to fix bugs. One pre-built binary image might not work on a different release. So it is hard to include useful pre-built binary images. At this point I don't want to bloat your package to support platforms that are not yet stable.

> The PR appears to enable scripting CLR from Node.js using node-chakracore, but not the reverse.

I haven't looked at that route... will take a look. I just ensured "npm test" pass.

**Comment by tjanczuk** [comment]
Given the node-chakracore churn, until it is appropriate time to include binary builds in the Edge package, perhaps we can then rely on the [EDGE_NATIVE](https://github.com/tjanczuk/edge#building-on-windows) environment variable to switch to a chakracore build rather than making the changes in the logic of locating the right binary?

**Comment by jianchun** [comment]
> Given the node-chakracore churn, until it is appropriate time to include binary builds in the Edge package, perhaps we can then rely on the EDGE_NATIVE environment variable to switch to a chakracore build rather than making the changes in the logic of locating the right binary?

That would work, just somehow inconvenient. Anybody trying out edge on node-chakracore needs to figure out how to build and how to set this env variable. Changes here automates it. We can "npm install" on a build machine with build tools, then test machines can "npm install build_share" to use the built binaries similarly to shipped pre-built binaries. Otherwise we'd need external scripts to build x86/x64, save to some share; clients need logic to figure out which binary to use and set env variable.

The changes in this PR are mostly generic, not node-chakracore specific. I just relaxed "known pre-compiled binaries" requirement on win32, added one more configuration for matching the current running node release.

**Comment by jianchun** [comment]
> The PR appears to enable scripting CLR from Node.js using node-chakracore, but not the reverse. Scripting Node.js from CLR is enabled with a NuGet package built using https://github.com/tjanczuk/edge/blob/master/tools/build_double.bat. Is there a reason this would not be supported?

Calling Node.js from CLR looks more difficult to customize. It looks possible but not as easy. The end result would be another nuget package? Maybe there's less demand. We could look at that later.

**Comment by jianchun** [comment]
BTW, I just discovered with my current changes here, edge still doesn't work smoothly with [Node.js (chakra)](http://aka.ms/node-chakra-installer), because the versionMap match is confused -- it also has version 5.6.x currently, incorrectly matched to pre-build binary 5.1.0. Workaround is just to run "tools\build.bat release" with this change. Or modify the logic further to avoid the incorrect match...

**Comment by jianchun** [comment]
Made an update so the known versionMap only applies to default Node.js with v8.

The 2nd commit "win32: try to build if no precompiled binaries" may sound like a bad idea. I put it in a separate commit so I can easily kill it if you request.

**Comment by tjanczuk** [comment]
@jianchun would you mind adding a section to readme with instructions on how to use edge with node-chakracore? Maybe a subsection of this: https://github.com/tjanczuk/edge#building-on-windows

**Comment by jianchun** [comment]
> @jianchun would you mind adding a section to readme with instructions on how to use edge with node-chakracore?

Added.

**Comment by jianchun** [comment]
Latest node-chakracore release has a fix on `new Error().stack`. Reverted one previous related change.

**Pull request closed without merging**
