### PR TITLE
fix domain crash

### PR DESCRIPTION
**Pull request by qumeta**
fix doamin crash and add type:Dictionary<Int32, object> MarshalCLRToV8

### CODE REVIEW

**Comment by mmanela** [comment]
@lilinghui Would this PR resolve this (#586) issue I filed around the fact that edge crashes when using appDomains?

**Comment by lilinghui** [comment]
@mmanela yes

**Comment by mmanela** [comment]
@tjanczuk Can you take a look at this PR? This will resolve possibly multiple open issues.

**Comment by agracio** [comment]
@lilinghui this solves AppDomain problem when running unit tests and when trying to forcefully run in new AppDomain using code, but on IIS/IIS Express Edge still throws AccessViolationException. Any chance you could take a look at it?

**Pull request closed without merging**
