### PR TITLE
CoreCLR compatibility

### PR DESCRIPTION
**Pull request by lstratman**
This is adds the ability for Edge.js to use the CoreCLR runtime instead of native or Mono.  The README.md file has been updated with all of the setup instructions and examples that I could think of.

Please be aware that there are a few URLs in various files that I updated to point to my (medicomp/edge) repository for testing purposes.  These include README.md, the package.json file, and both of the Linux setup scripts under tools.

### CODE REVIEW

**Comment by tjanczuk** [comment]
@lstratman fantastic work, thank you!

This is a major change and I would like to spend some quality time on the PR, so please bear with me.

**Comment by lstratman** [comment]
A few things of note in my recent commits:

1. I'm now targeting the stable CoreCLR branch, currently on 1.0.0-beta8, as opposed to the (close to) nightly build branch.  Once the next beta drops, I'm going to have to make a few updates due to some classes being moved around, but it's just much easier to target beta8 right now since I don't have to worry about the NuGet packages being out of sync with the CLR.
2. Dynamic compilation is now supported from the project.json file.  This means that if you have a CoreCLR .NET app in a directory (with a project.json) and you point EDGE_APP_DIR at that directory, you can reference its types from Edge.js without first having to build the application and then having to point Edge.js at the build artifacts.  For example, if you have a project in c:\src\MyProject, using it with Edge.js goes from this:

````javascript
edge.func({
    assemblyFile: 'c:\\src\\MyProject\\bin\\Release\\dnxcore50\\MyProject.dll',
    typeName: 'MyType',
    methodName: 'MyMethod'
});
````

to:

````javascript
edge.func({
    assemblyFile: 'MyProject',
    typeName: 'MyType',
    methodName: 'MyMethod'
});
````

This was the last of the "feature work" that I have planned.  From now on I'll be fixing any bugs that you discover and making Edge.js compatible with the latest CoreCLR betas as they become available.

**Comment by NightOwl888** [comment]
@lstratman 

FYI - [Beta 8 is the last beta planned](https://github.com/aspnet/Home/wiki/Roadmap). The next release will be RC1.

**Comment by tjanczuk** [comment]
@lstratman This looks great. I am almost done going through this code. I am planning to merge this into tjanczuk:coreclr, do fixups there (links etc), then merge into master.

**Comment by lstratman** [comment]
There is a showstopper that appears to be a bug in CoreCLR that will prevent Edge.js from working at all with x86 instances of CoreCLR.  I had been doing all of my testing under CoreCLR x64 (which still works perfectly and can continue to be used for testing), so I didn't catch it until now.  I have [submitted a bug](https://github.com/dotnet/coreclr/issues/2059) to the CoreCLR team which will need to be resolved before this PR can be merged into master.

**Comment by tjanczuk** [comment]
I think it is perfectly OK for now if Edge works only with x64 CoreCLR (and node). I am assuming CoreCLR will fix it for RC/RTM.

**Comment by jskulavik** [comment]
@lstratman: I'm giving your CoreCLR build instructions a go on Windows while patiently waiting for @tjanczuk's pull, and I noticed that you specify that we need VS2013 for --msvs_version.  Any reason that wouldn't work with VS2015 that you know of?

**Comment by lstratman** [comment]
@jskulavik Nope, VS2015 should work just fine.

**Comment by jskulavik** [comment]
@lstratman Okay, thanks, and thanks again for this awesome effort!

**Comment by axefrog** [comment]
Just a note- if you only support x64, edge.js won't be deployable to free Azure websites.

**Comment by lstratman** [comment]
@axefrog This should just be a temporary situation, as I fully expect MS to have fixed the bug by the time RTM rolls around.  Someone's looking into it now.

RC1 has dropped, so I'll spend the next day or two fixing assembly references and class names to make everything compatible.  I'll let you all know when that's complete.

**Comment by jskulavik** [comment]
@lstratman: when you update to RC1, would you mind updating the MD install instructions as well?  I wasn't able to complete your "install and build on Windows" as I ran into a node-gyp error that keeps me from building and using edge_*.node

**Comment by lstratman** [comment]
@jskulavik Those instructions should work, what's the error that you're seeing?

**Comment by jskulavik** [comment]
@lstratman Funky msbuild issues:
image

**Comment by lstratman** [comment]
That was significantly easier than I was expecting.  We are now compatible with RC1.

**Comment by lstratman** [comment]
@jskulavik It looks like it can't find msvcmrt.lib.  Can you try running the build from a VS command prompt instead of just a regular command prompt?

**Comment by jskulavik** [comment]
@lstratman Will do.  I may have missed this earlier, but you're providing the edge_*.node in lib/native so really, there's no need to build just to get running, correct?

**Comment by lstratman** [comment]
For Windows, yes, we provide the pre-built binaries so there's no need for compilation.  Compilation is only necessary on Linux and OS X.

**Comment by jskulavik** [comment]
Thanks, that's what I noticed when pulling down your updates for RC1.  I still want to be able to build though, so I'll continue ahead with trying to build on Windows.  Thanks!

**Comment by tjanczuk** [comment]
This has been an amazing effort @lstratman, I kicked the tires left and right on this PR and really have nothing to add. Thank you. 

I am merging this into edge/coreclr now, will do the fixups (links) there, then merge into main. Before I ship on NPM I want to update to latest Node, so it may be still a few days before it is on NPM (I am currently traveling). 

After this is in master, it would be great if you could make any subsequent PRs directly against master. They will sure be appreciated.

**Comment by tjanczuk** [comment]
@lstratman I also need the changes you made in edge-cs. Can you make a PR?

**Comment by lstratman** [comment]
Fantastic, glad it worked out so well.  PR for edge-cs is https://github.com/tjanczuk/edge-cs/pull/6

**Comment by tjanczuk** [comment]
This is now in master. 

I plan to update Node versions and Dockerfile, then publish on NPM and provide a docker image. The experience of getting all prerequisites installed is a bit overwhelming with the addition of CoreCLR.

**Comment by dpolivy** [comment]
@lstratman @jskulavik I'm trying to build `master` (which has this PR) in a VS2015 command prompt, and am running into the same MSVCMRT.lib error. I'm trying to build edge in order to get the symbols so I can debug an issue.

`LINK : fatal error LNK1104: cannot open file 'MSVCMRT.lib'`

Any ideas?

**Pull request merged**
