### PR TITLE
add iojs compiling to build scripts - added iojs 2.3.1

### PR DESCRIPTION
**Pull request by wouterverweirder**
this pull request updates the build scripts to support compilation for io.js + adds version 2.3.1 to the list of supported versions & precompiled files.

It should be fairly easy to add extra versions of iojs, as long as nan supports it.

users will need to npm install pangyp if they want to compile on / for io.js - as mentioned by the update batch file.

### CODE REVIEW

**Comment by tjanczuk** [comment]
Thank you for the PR. A few questions: 

1. Did you test it on OSX and Linux as well as Windows?
2. Are all tests passing?
3. I notice the 2.3.1 version of iojs is explicitly listed as the one supported. Can this support be extended to 2.3.x instead? Is 3.x also supported?

**Comment by wouterverweirder** [comment]
1. Only tested on windows. I am using nvmw to manage multiple node installations. This might have impact on looking up pangyp in the build.bat script (as my node is not in %APPDATA% but in  a subdirectory of my %NODEDIR%. In general the batch scripts could be improved to handle different node setups (just node, or managed with nvmw / nvm)
2. Getting a "module did not self-register" error when trying to run the tests. I will need to look into the build script for the test dll.
3. I chose this version as this is the version I'm currently using for a project. I think that as long as nan supports that version of node / io.js we should be fine. However: there has been quite some changes in nan 2.x, so there will need to be changes to the native code for these newer releases of nan.

**Comment by wouterverweirder** [comment]
Update on 2: errors occured when using node.exe as a filename to test the iojs builds. I've updated the download & batch scripts to check the version nr and use iojs.exe when targetting iojs. This allowed the testall.bat to run & complete all tests successfully :-)

**Comment by tjanczuk** [comment]
@wouterverweirder thank you for your work here, but with the merge of Node.js and io.js I've decided to target Node.js 4 with the next version of edge. edge@4.0.0 with such support just shipped.

**Pull request closed without merging**
