### PR TITLE
Marshalling strongly typed objects containing enums from .NET to Node.js

### PR DESCRIPTION
**Pull request by ludoviclefevre**
Related to issue #183, this is a first attempt to marshal enum values as integer. I don't have mono environnment yet so I only edited .NET code for the moment. An environmment variable (EDGE_MARSHAL_ENUM_AS_INT) set to 1 enable this behaviour, if not set default behavior is the same as before (string).

### CODE REVIEW

**Comment by nkinnan** [comment]
Thanks for adding this option.  I am unable to see any effect by setting the environment variable to "1".  Is this in the latest release?  If not, how do I get this functionality?  Sorry, new to github here, but really need this feature.  Thanks!

**Comment by ludoviclefevre** [comment]
Hi Tomasz,

I synced the fork with the upstream repository. Do you think you could reintegrate it to the main project?

thanks.

Ludovic

**Comment by ludoviclefevre** [comment]
Sorry, i deleted the fork. I will create a new pull request.

**Comment by tjanczuk** [comment]
I was just looking for this PR as I plan to cut edge 0.10.1 with the fix for missing msvcp120.dll dependency on windows. I will include your changes in subsequent release then.

**Comment by ludoviclefevre** [comment]
Thanks, I closed this pull request and creates a new one because I tried to change author info on commits of some of my repositories (it was a bad idea :-) ). So this is the new pull request:

https://github.com/tjanczuk/edge/pull/248

it will be helpful for my project if you can include these changes in one of the next releases.

Thanks

**Pull request closed without merging**
